using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace wpf_tutorial.XAML_versus_CodeBehind
{
    /// <summary>
    /// Interaction logic for Buttons.xaml
    /// </summary>
    public partial class Buttons : Window
    {
        public Buttons()
        {
            InitializeComponent();

            var btn = CreateNewButton();
            container.Children.Add(btn);
        }

        private Button CreateNewButton()
        {
            var btn = new Button();
            btn.FontWeight = FontWeights.Bold;

            var panel = new WrapPanel();

            var txt = new TextBlock();
            txt.Text = "I'm generated by code-behind";
            panel.Children.Add(txt);

            btn.Content = panel;

            return btn;
        }
    }
}
